### ISSUE TITLE
Text rendering looks off for openfl

### ISSUE THREAD

**Issue by bguiz** [YellowAfterlife/openfl-bitfive#35]
This is what the same program, the [Pathfinding demo](http://haxeflixel.com/demos/Pathfinding/) looks like with the html5 target using bitfive:

![bitfive-text](https://cloud.githubusercontent.com/assets/1773785/5236975/7290319e-78b5-11e4-829d-0589c8c37829.png)

... and here is what is looks like in the neko/ flash targets:

![neko-text](https://cloud.githubusercontent.com/assets/1773785/5236976/870ccb28-78b5-11e4-869b-74519e3dcc95.png)

The issues are:

- Text colour in the buttons are white instead of black,
- Text appears to be very faint/ thin
- Center alignment of the text in the button appears to be ignored
- Multiline text appears to be all printed in a single line

Done using flixel-demos: `/usr/lib/haxe/lib/flixel-demos/1,1,1/Flixel Features/Pathfinding`:

    $ haxelib list
    actuate: [1.7.5]
    flixel-addons: [1.1.0]
    flixel-demos: [1.1.1]
    flixel-templates: [1.0.2]
    flixel-tools: [1.0.2]
    flixel-ui: [1.0.2]
    flixel: 3.3.5 [3.3.6]
    hxcpp: [3.1.39]
    lime: 2.0.0-alpha.7 [2.0.0]
    openfl-bitfive: 2.0.1 [2.1.6]
    openfl-samples: [2.1.0]
    openfl: 2.1.5 [2.1.6]
    swf: [1.7.0] 1.6.9 1.6.7

**Comment by YellowAfterlife** [comment]
Well then.
