### ISSUE TITLE
latest compatible haxeflixel version?

### ISSUE THREAD

**Issue by zimmy87** [YellowAfterlife/openfl-bitfive#41]
Hi I'm trying to build a haxeflixel 3.3.8 game with an HTML5 target and have been finding the default openfl target to be pretty sluggish, so before I dive into trying to optimize the output of that I was looking to see if bitfive could get me a faster version but when I compile, I get a ton of "openfl.* should be flash.*" errors like so:

bin/html5/haxe/ApplicationMain.hx:68: characters 23-53 : NMEPreloader should be flash.display.DisplayObject
bin/html5/haxe/ApplicationMain.hx:68: characters 23-53 : For function argument 'o'
bin/html5/haxe/ApplicationMain.hx:249: characters 26-35 : NMEPreloader should be flash.display.DisplayObject
bin/html5/haxe/ApplicationMain.hx:249: characters 26-35 : For function argument 'o'
C:\HaxeToolkit\haxe\lib\openfl/2,0,1/backends/html5/openfl/display/BitmapData.hx:800: characters 21-31 : flash.geom.Rectangle should be openfl.geom.Rectangle
C:\HaxeToolkit\haxe\lib\openfl/2,0,1/backends/html5/openfl/display/BitmapData.hx:800: characters 21-31 : For function argument 'rect'
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:22: characters 8-14 : flash.display.BitmapData should be openfl.display.BitmapData
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:22: characters 8-14 : For function argument 'image'
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:20: lines 20-26 : Missing super constructor call
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:34: characters 15-27 : flash.geom.Rectangle should be openfl.geom.Rectangle
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:34: characters 15-27 : For function argument 'rectangle'
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:75: characters 14-18 : flash.geom.Rectangle should be openfl.geom.Rectangle
C:\HaxeToolkit\haxe\lib\flixel/3,3,8/flixel/system/layer/TileSheetExt.hx:75: characters 14-18 : For function argument 'rectangle'
bin/html5/haxe/DefaultAssetLibrary.hx:110: lines 110-114 : Field getBitmapData overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:110: lines 110-114 : id : String -> openfl.display.BitmapData should be id : String -> flash.display.BitmapData
bin/html5/haxe/DefaultAssetLibrary.hx:110: lines 110-114 : openfl.display.BitmapData should be flash.display.BitmapData
bin/html5/haxe/DefaultAssetLibrary.hx:129: lines 129-142 : Field getBytes overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:129: lines 129-142 : id : String -> openfl.utils.ByteArray should be id : String -> flash.utils.ByteArray
bin/html5/haxe/DefaultAssetLibrary.hx:129: lines 129-142 : openfl.utils.ByteArray should be flash.utils.ByteArray
bin/html5/haxe/DefaultAssetLibrary.hx:116: lines 116-119 : Field getFont overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:116: lines 116-119 : id : String -> openfl.text.Font should be id : String -> flash.text.Font
bin/html5/haxe/DefaultAssetLibrary.hx:116: lines 116-119 : openfl.text.Font should be flash.text.Font
bin/html5/haxe/DefaultAssetLibrary.hx:125: lines 125-127 : Field getMusic overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:125: lines 125-127 : id : String -> openfl.media.Sound should be id : String -> flash.media.Sound
bin/html5/haxe/DefaultAssetLibrary.hx:125: lines 125-127 : openfl.media.Sound should be flash.media.Sound
bin/html5/haxe/DefaultAssetLibrary.hx:121: lines 121-123 : Field getSound overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:121: lines 121-123 : id : String -> openfl.media.Sound should be id : String -> flash.media.Sound
bin/html5/haxe/DefaultAssetLibrary.hx:121: lines 121-123 : openfl.media.Sound should be flash.media.Sound
bin/html5/haxe/DefaultAssetLibrary.hx:165: lines 165-178 : Field loadBitmapData overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:165: lines 165-178 : id : String -> h : (openfl.display.BitmapData -> Void) -> Void should be id : String -> h : (flash.display.BitmapData -> Void) -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:165: lines 165-178 : openfl.display.BitmapData -> Void should be flash.display.BitmapData -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:192: lines 192-206 : Field loadBytes overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:192: lines 192-206 : id : String -> h : (openfl.utils.ByteArray -> Void) -> Void should be id : String -> h : (flash.utils.ByteArray -> Void) -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:192: lines 192-206 : openfl.utils.ByteArray -> Void should be flash.utils.ByteArray -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:180: lines 180-182 : Field loadFont overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:180: lines 180-182 : id : String -> h : (openfl.text.Font -> Void) -> Void should be id : String -> h : (flash.text.Font -> Void) -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:180: lines 180-182 : openfl.text.Font -> Void should be flash.text.Font -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:188: lines 188-190 : Field loadMusic overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:188: lines 188-190 : id : String -> h : (openfl.media.Sound -> Void) -> Void should be id : String -> handler : (flash.media.Sound -> Void) -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:188: lines 188-190 : openfl.media.Sound -> Void should be flash.media.Sound -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:184: lines 184-186 : Field loadSound overloads parent class with different or incomplete type
bin/html5/haxe/DefaultAssetLibrary.hx:184: lines 184-186 : id : String -> h : (openfl.media.Sound -> Void) -> Void should be id : String -> handler : (flash.media.Sound -> Void) -> Void
bin/html5/haxe/DefaultAssetLibrary.hx:184: lines 184-186 : openfl.media.Sound -> Void should be flash.media.Sound -> Void
Build halted with errors.
Done(1)

I've tried build with the following:

actuate: 1.7.5 [1.8.4]
flixel-addons: [1.1.0]
flixel: [3.3.8]
hscript: 2.0.1 [2.0.4]
lime-tools: [1.5.7]
lime: [2.3.3]
openfl-bitfive: [3.0.0]
openfl: [3.0.3]

I also read on stackoverflow that there could be incompatibilities with newer versions of openfl ( http://stackoverflow.com/questions/26707782/how-to-use-haxeflixel-together-with-openfl-bitfive ), so I also tried the following:

actuate: 1.7.5 [1.8.4]
flixel-addons: [1.1.0]
flixel: [3.3.8]
hscript: 2.0.1 [2.0.4]
lime-tools: [1.5.7]
lime: [1.0.1] 
openfl-bitfive: [2.1.6]
openfl: [2.0.1] 

but I'm still seeing similar errors. Is it the version of flixel that's messing me up here or am I doing something else wrong?

**Comment by YellowAfterlife** [comment]
Before anything else, try opening HaxeFlixel' haxelib.json (located in haxe/lib/flixel/3,3,8) and removing "openfl" from the dependencies list. Recently something has massively broke with the way library dependencies are loaded in Haxe and libraries with dependencies now cause Haxe to include them multiple times (once with and once without xml config in mind), in this case mixing openfl-bitfive and normal openfl classes. Needless to say, that yields endless errors.

**Comment by zimmy87** [comment]
YES!

removing "openfl" from the dependencies and also removing it from the classpaths in my project got the project to build finally. going to be doing some testing soon on inserting this in a Windows Store App and deploying to a Surface tablet. Thank you for the quick reply and assistance!

**Comment by FryDay** [comment]
@YellowAfterlife I tried your suggestion, but still no dice :(

**Comment by YellowAfterlife** [comment]
@FryDay Are you getting the same errors? And are you using additional libraries? If any of them have openfl on dependency list, you'll need to remove it from there as well.

**Comment by YellowAfterlife** [comment]
Closing as it is/was a haxelib inclusion problem rather than something related to this particular library.
