### ISSUE TITLE
Error stat [asset path] with assets from haxelib include.xml files

### ISSUE THREAD

**Issue by Gama11** [YellowAfterlife/openfl-bitfive#42]
Steps to reproduce:

- set up a dummy haxelib with an `include.xml` that includes any asset:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project>
	<assets path="assets" />
</project>
```

- put at least one file into `assets/`
- include the haxelib in the bitfive project you're testing with

This leads to the following error:

```
C:\HaxeToolkit\haxe\std/neko/_std/sys/FileSystem.hx:42: characters 21-47 : Error stat assets/LICENSE
Export/html5/haxe/ApplicationMain.hx:229: characters 18-51 : Called from
Export/html5/haxe/ApplicationMain.hx:17: characters 2-7 : Called from
Aborted
Build halted with errors.
```

Tested with Haxe 3.2.0, Lime 2.4.1 and OpenFL 3.0.6.
HaxeFlixel is affected by this issue.

**Comment by YellowAfterlife** [comment]
Revealed to be introduced by https://github.com/YellowAfterlife/openfl-bitfive/commit/e2fd53d99d209dc0c077cf437f63daa835882655
Fixed in https://github.com/YellowAfterlife/openfl-bitfive/commit/696baf6cb9ca9a00cbec8f984aa94f01aa5aabff
