### ISSUE TITLE
html5 runtime error on current openfl version (3.3.3)

### ISSUE THREAD

**Issue by weilitao** [YellowAfterlife/openfl-bitfive#44]
Hello. when I use openfl to create a sample project, the building process is ok. But when running inside a browser, following error occurred:

DisplayingABitmap.js:1811 Uncaught TypeError: Cannot read property 'mouseMove' of undefined

The error context code:

-----------------------------
$hxClasses["haxe.ds.StringMap"] = haxe_ds_StringMap;
haxe_ds_StringMap.__name__ = ["haxe","ds","StringMap"];
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	set: function(key,value) {
		if(__map_reserved[key] != null) this.setReserved(key,value); else this.h[key] = value;
// above is the error line
	}
	,get: function(key) {
		if(__map_reserved[key] != null) return this.getReserved(key);
		return this.h[key];
	}

---------------------------
The sample project: 
openfl create DisplayingABitmap

The library I use:
openfl: 3.3.3
lime: 2.6.2
openfl-bitfive: 3.3.2

**Comment by YellowAfterlife** [comment]
In fact is a problem with Haxe standard library, https://github.com/HaxeFoundation/haxe/issues/4533
Haxe 3.1.3 did not yet spot that breaking implementation.
I'll see if I can add a workaround for this.

**Comment by YellowAfterlife** [comment]
Fixed in https://github.com/YellowAfterlife/openfl-bitfive/commit/7000f947728be93b03fe87f2c03c944179545a7a
